// src/components/Navbar.jsx
function Navbar() {
  return (
    <div>
      <div className=  ' justify-center flex' >
        <nav className=' rounded-full shadow px-8 py-2 bg-white '>
          <ul className='flex font-semibold text-base space-x-2   sm:text-lg sm:space-x-6  '>
            <li className='hover:text-gray-300 transition-colors'>Home</li>
            <li className='hover:text-gray-300 transition-colors'>About</li>
            <li className='hover:text-gray-300 transition-colors'>Projects</li>
            <li className='hover:text-gray-300 transition-colors'>Contacts</li>
          </ul>
        </nav>
      </div>
    </div>
  );
}
export default Navbar;

// src/components/Navbar.vue
<script setup>

</script>

<template>
<div class=" justify-center flex mt-6">
  <nav class=" rounded-full shadow px-8 py-2 ">
    <ul class="flex font-semibold text-base space-x-2   sm:text-lg sm:space-x-6  ">
      <li class="hover:text-gray-300 transition-colors">Home</li>
      <li class="hover:text-gray-300 transition-colors">About</li>
      <li class="hover:text-gray-300 transition-colors">Projects</li>
      <li class="hover:text-gray-300 transition-colors">Contacts</li>
    </ul>
  </nav>
</div>
</template>

<style scoped>

</style>
